import type { AIModel } from "@/lib/types";

export const DEFAULT_MODELS: AIModel[] = [
  {
    id: "openai/gpt-oss-120b",
    name: "Apex — 4B Trained (Groq LPU)",
    type: "deep_reasoning",
    speed: "fast",
    max_tokens: 4096,
    description: "High-capacity parameter model hosted on Groq LPUs for zero-hallucination compliance and deep diagnostics.",
    recommended_for: "Complex cross-document verification & root cause analysis",
    supports_vision: false,
    provider: "groq",
  },
  {
    id: "openai/gpt-oss-20b",
    name: "Forge — 2B Diagnostics (Groq Fast)",
    type: "fast",
    speed: "ultra_fast",
    max_tokens: 4096,
    description: "High-speed Groq model for multi-step mechanical diagnostics and procedure generation.",
    recommended_for: "Multi-step repair procedures",
    supports_vision: false,
    provider: "groq",
  },
  {
    id: "groq/compound-mini",
    name: "Nord — 1B Fast Edge (Groq)",
    type: "fast",
    speed: "instant",
    max_tokens: 4096,
    description: "Sub-100ms ultra-fast Groq LPU model for rapid error code lookups and symptom triage.",
    recommended_for: "Rapid error code lookups (<100ms)",
    supports_vision: false,
    provider: "groq",
  },
  {
    id: "llama-3.3-70b-versatile",
    name: "Llama 3.3 70B Versatile",
    type: "deep_reasoning",
    speed: "fast",
    max_tokens: 4096,
    description: "Meta's flagship 70B versatile reasoning model on Groq for technical document synthesis.",
    recommended_for: "General industrial Q&A",
    supports_vision: false,
    provider: "groq",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    type: "general",
    speed: "fast",
    max_tokens: 1024,
    description: "High-speed multimodal foundation model by Google with vision inspection capability.",
    recommended_for: "Multimodal image & schematic inspection",
    supports_vision: true,
    provider: "gemini",
  },
];
