import type { AIModel } from "@/lib/types";

export const DEFAULT_MODELS: AIModel[] = [
  {
    id: "deep101godhani/mendx-apex-v3",
    name: "MEND-X Apex v3 (Custom HF Cloud)",
    type: "custom_cloud",
    speed: "ultra_fast",
    max_tokens: 4096,
    description: "Fine-tuned proprietary QLoRA adapter for industrial machine triage, fault root-cause analysis, and safety directives.",
    recommended_for: "Factory floor diagnostics & proprietary troubleshooting",
    supports_vision: true,
    provider: "huggingface",
  },
  {
    id: "deep101godhani/nord",
    name: "MEND-X Nord (HF Cloud)",
    type: "fast",
    speed: "instant",
    max_tokens: 2048,
    description: "Ultra-fast low-latency cloud model fine-tuned for quick error code definitions and parameter checks.",
    recommended_for: "Quick error code lookups (<100ms)",
    supports_vision: false,
    provider: "huggingface",
  },
  {
    id: "gpt-oss:20b",
    name: "GPT-OSS 20B (Active)",
    type: "deep_reasoning",
    speed: "ultra_fast",
    max_tokens: 4096,
    description: "Deep reasoning engine running on Ollama Cloud / Local for multi-step mechanical verification.",
    recommended_for: "Multi-step diagnostics & reasoning",
    supports_vision: false,
    provider: "ollama",
  },
  {
    id: "openai/gpt-oss-120b",
    name: "GPT-OSS 120B (Groq)",
    type: "deep_reasoning",
    speed: "fast",
    max_tokens: 4096,
    description: "High-capacity 120B parameter model hosted on Groq LPUs for zero-hallucination compliance.",
    recommended_for: "Complex cross-document verification",
    supports_vision: false,
    provider: "groq",
  },
  {
    id: "llama-3.3-70b-versatile",
    name: "Llama 3.3 70B Versatile",
    type: "deep_reasoning",
    speed: "fast",
    max_tokens: 4096,
    description: "Meta's flagship 70B versatile reasoning model for technical document synthesis.",
    recommended_for: "General industrial Q&A",
    supports_vision: false,
    provider: "groq",
  },
  {
    id: "gemini-2.5-flash",
    name: "Gemini 2.5 Flash",
    type: "general",
    speed: "fast",
    max_tokens: 1024,
    description: "High-speed multimodal foundation model by Google with vision inspection capability.",
    recommended_for: "Multimodal image & schematic inspection",
    supports_vision: true,
    provider: "gemini",
  },
];
