"""Generate synthetic test PDFs for MechMind demo.

Run with:
    pip install reportlab
    python scripts/create_demo_pdfs.py

Output: backend/demo_manuals/
"""
from __future__ import annotations

import os
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
)

OUT_DIR = Path(__file__).parent.parent / "demo_manuals"
OUT_DIR.mkdir(exist_ok=True)

STYLES = getSampleStyleSheet()
TITLE_STYLE = ParagraphStyle("Title2", parent=STYLES["Title"], fontSize=20, spaceAfter=12)
H1_STYLE = ParagraphStyle("H1", parent=STYLES["Heading1"], fontSize=14, spaceAfter=8)
BODY_STYLE = ParagraphStyle("Body", parent=STYLES["Normal"], fontSize=10, spaceAfter=6)
WARN_STYLE = ParagraphStyle(
    "Warning", parent=STYLES["Normal"], fontSize=10,
    textColor=colors.darkred, spaceAfter=6, spaceBefore=4,
)


def spacer() -> Spacer:
    return Spacer(1, 0.4 * cm)


def title_page(elements: list, title: str, model: str, manufacturer: str) -> None:
    elements.append(spacer())
    elements.append(Paragraph(title, TITLE_STYLE))
    elements.append(Paragraph(f"Model: {model}", BODY_STYLE))
    elements.append(Paragraph(f"Manufacturer: {manufacturer}", BODY_STYLE))
    elements.append(Paragraph("For service technician use only.", BODY_STYLE))
    elements.append(spacer())


def error_table(elements: list, heading: str, rows: list[tuple]) -> None:
    elements.append(Paragraph(heading, H1_STYLE))
    elements.append(spacer())
    header = ["Code", "Description", "Probable Cause", "Corrective Action"]
    table_data = [header] + list(rows)
    tbl = Table(table_data, colWidths=[2.5 * cm, 4.5 * cm, 5 * cm, 7 * cm])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.whitesmoke, colors.white]),
        ("GRID", (0, 0), (-1, -1), 0.4, colors.grey),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("WORDWRAP", (0, 0), (-1, -1), True),
    ]))
    elements.append(tbl)
    elements.append(spacer())


def build_haas_vf2() -> None:
    path = OUT_DIR / "HaasVF2_Service_Manual.pdf"
    doc = SimpleDocTemplate(str(path), pagesize=A4)
    elements: list = []

    title_page(elements, "Haas VF-2 Service Manual", "VF-2", "Haas Automation")

    elements.append(Paragraph("Error Code Reference", H1_STYLE))
    elements.append(Paragraph(
        "This section lists alarm codes displayed on the Haas control panel. "
        "Always disconnect power before performing maintenance unless otherwise stated.",
        BODY_STYLE,
    ))
    elements.append(spacer())

    rows = [
        (
            "E101",
            "Cooling system pressure loss",
            "Coolant pump failure or blocked filter",
            "1. Check coolant level\n2. Inspect pump\n3. Replace filter if blocked",
        ),
        (
            "E202",
            "Spindle overload",
            "Feed rate too high or tool wear",
            "1. Reduce feed rate\n2. Inspect tool for wear\n3. Replace tool if needed",
        ),
        (
            "E303",
            "X-axis servo fault",
            "Encoder failure or drive fault",
            "1. Check axis drive LED\n2. Reseat encoder cable\n3. Contact Haas service",
        ),
    ]
    error_table(elements, "Alarm Codes", rows)

    elements.append(Paragraph(
        "WARNING: Disconnect power before opening coolant reservoir.",
        WARN_STYLE,
    ))

    doc.build(elements)
    print(f"  Written: {path}")


def build_fanuc_oi_mf() -> None:
    path = OUT_DIR / "FanucOiMF_Service_Manual.pdf"
    doc = SimpleDocTemplate(str(path), pagesize=A4)
    elements: list = []

    title_page(elements, "Fanuc 0i-MF Service Manual", "0i-MF", "Fanuc Corporation")

    elements.append(Paragraph("Alarm Code Reference", H1_STYLE))
    elements.append(Paragraph(
        "This section describes alarms generated by the Fanuc 0i-MF series controller. "
        "Note: alarm numbers overlap with machine builder codes — always identify "
        "the source before acting.",
        BODY_STYLE,
    ))
    elements.append(spacer())

    rows = [
        (
            "E101",
            "Motor overload detected",
            "Motor current exceeded limit",
            "1. Check motor connections\n2. Verify load not exceeding specifications\n"
            "3. Reset alarm and monitor current",
        ),
        (
            "E202",
            "Communication fault",
            "Network cable disconnected",
            "1. Check Ethernet cable\n2. Verify network settings\n3. Restart controller",
        ),
        (
            "E404",
            "Program error",
            "Invalid G-code command",
            "1. Check program at line indicated\n2. Verify G-code syntax",
        ),
    ]
    error_table(elements, "Alarm Codes", rows)

    elements.append(Paragraph(
        "WARNING: Motor may be hot — allow cooling before touching.",
        WARN_STYLE,
    ))

    doc.build(elements)
    print(f"  Written: {path}")


def build_kuka_kr6() -> None:
    path = OUT_DIR / "KUKA_KR6_Robot_Manual.pdf"
    doc = SimpleDocTemplate(str(path), pagesize=A4)
    elements: list = []

    title_page(elements, "KUKA KR6 Robot Manual", "KR6", "KUKA Robotics")

    elements.append(Paragraph("Fault Messages", H1_STYLE))
    elements.append(Paragraph(
        "Fault codes are displayed on the smartPAD. Use the KRC4 log to view "
        "full fault history. Robot faults use the F-prefix numbering scheme.",
        BODY_STYLE,
    ))
    elements.append(spacer())

    rows = [
        (
            "F101",
            "Base joint position error",
            "Joint exceeded software limit",
            "1. Move robot to home position manually\n2. Reset fault\n"
            "3. Verify joint limits in configuration",
        ),
        (
            "F202",
            "Arm joint overload",
            "Payload exceeded rated capacity",
            "1. Check attached payload weight\n2. Reduce speed if payload is at maximum\n"
            "3. Inspect mechanical stops",
        ),
    ]
    error_table(elements, "Fault Codes", rows)

    elements.append(Paragraph(
        "WARNING: Ensure area is clear before moving robot.",
        WARN_STYLE,
    ))

    doc.build(elements)
    print(f"  Written: {path}")


def main() -> None:
    print(f"Generating demo PDFs in: {OUT_DIR}")
    build_haas_vf2()
    build_fanuc_oi_mf()
    build_kuka_kr6()
    print("\nDone. Upload these files via the MechMind admin UI to enable RAG queries.")


if __name__ == "__main__":
    main()
